[dynarmic] add tuple constructor to Matcher
GetName, GetNameArm, and other similar functions introduced lately initialize
a `std::vector<std::pair>` from a macro-expanded brace list:

    std::vector<std::pair<std::string_view, Matcher<V>>> list = {
        { name, DYNARMIC_DECODER_GET_MATCHER(...) },
        ...
    };

... but DYNARMIC_DECODER_GET_MATCHER returns `std::tuple<u32, u32>`, which cannot
initialize Matcher<V> on my side:

    error: could not convert ‘{{"VMLA", ...}’
    from ‘<brace-enclosed initializer list>’ to ‘...’

This commit adds an explicit tuple constructor so it compiles.